# This file was generated by GoReleaser. DO NOT EDIT.
cask "harvest-cli" do
  version "0.5.2"

  on_macos do
    on_arm do
      sha256 "a44f83b5652601db43183de981d62e03ad05298028ad2400f9cd1f565eaed319"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e2d1191bb384aec9606d27d174b0d05749f11668c641f8e602531502129587d1"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bbe9ef12fa70f946876c60d4f4500ba64cf22f73e6832e7619702bd58fa0044d"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5bb61f25b8ccb0c6e4cdbb72545f1a6222f1436bc4994168b8ade53b0e54262f"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_amd64.tar.gz"
    end
  end

  name "harvest-cli"
  desc "A command-line tool for managing your Harvest time entries, projects, and tasks"
  homepage "https://github.com/jc00ke/harvest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harvest"
  bash_completion "completions/harvest.bash"
  fish_completion "completions/harvest.fish"
  zsh_completion "completions/harvest.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harvest"]
    end
  end

  # No zap stanza required
end
