# This file was generated by GoReleaser. DO NOT EDIT.
cask "harvest" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "cb80d919d1ec5877653b9b1fe87eb48730701fd47d172d1b38800a3baa5accd0"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "33c8ec04d785e8d7f14a3588cbaea5356136f30c3bfe24d89a15fd9fa6ebebef"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "756a00c1bc6986c5e4dd47cebb952f8ee73e2e653a64223fcec1f80a975ef01e"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3a741e007787a0063885c40650c81e7c50f6d95deba5512794c9e68d5d8bd5a"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_arm64.tar.gz"
    end
  end

  name "harvest"
  desc "A command-line tool for managing your Harvest time entries, projects, and tasks"
  homepage "https://github.com/jc00ke/harvest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harvest"
  bash_completion "completions/harvest.bash"
  fish_completion "completions/harvest.fish"
  zsh_completion "completions/harvest.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harvest"]
    end
  end

  # No zap stanza required

end
