# This file was generated by GoReleaser. DO NOT EDIT.
cask "harvest" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "1c3d066e8c43a586c0467f3a113a6945034bd9623f79ff735b363058dc3bb865"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76f2aaef2647a1ae44e6f890151dd461a45d60208b26def1bdd1b0448d999a81"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e95c1a5521fabe0deb950c98e9676fbc1f39b0139085d43afe77da8df6dfdb07"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f517684af9638a0142e684f2dcf21f9ec26ef739b45fbb97bc32d71ec7ffc3f9"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_arm64.tar.gz"
    end
  end

  name "harvest"
  desc "A command-line tool for managing your Harvest time entries, projects, and tasks"
  homepage "https://github.com/jc00ke/harvest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harvest"
  bash_completion "completions/harvest.bash"
  fish_completion "completions/harvest.fish"
  zsh_completion "completions/harvest.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harvest"]
    end
  end

  # No zap stanza required

end
