# This file was generated by GoReleaser. DO NOT EDIT.
cask "harvest" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "97f353458defdcb33264000a7ecec088a7c2a5d2e08d469d0f0aebf7e9a84b9f"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "916ce70bd0f3d69c64fd02b952589d776016ed3b9536ff87970156596dbfd13b"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c67874b04f1b7f688a9041116b99ada1927c98ffcd14e7afe80f8fdaea256e92"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cbbd0c8075039133c38e6f4ba3ad9096038a9ad2ba0800a9c7b546edebe1741"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_arm64.tar.gz"
    end
  end

  name "harvest"
  desc "A command-line tool for managing your Harvest time entries, projects, and tasks"
  homepage "https://github.com/jc00ke/harvest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harvest"
  bash_completion "completions/harvest.bash"
  fish_completion "completions/harvest.fish"
  zsh_completion "completions/harvest.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harvest"]
    end
  end

  # No zap stanza required

end
