# This file was generated by GoReleaser. DO NOT EDIT.
cask "harvest-cli" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "240c5c5710dcf79f3bd56a32264d9121f9cd86dd15747fe48b5d69c58766ebbd"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "09c786e521d76aa80b94fb3b399ce487f8bbc00cd481e1ff07bf7b16411013da"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "352cc1d499516b9ab240fb04c35182c0318e1298ff9aec40fba5b74ef318889e"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "08523946c4e29bf7fac9c4ad7f1147eeeb13193ee6a524225c1c91ba2f5b3224"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_arm64.tar.gz"
    end
  end

  name "harvest-cli"
  desc "A command-line tool for managing your Harvest time entries, projects, and tasks"
  homepage "https://github.com/jc00ke/harvest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harvest"
  bash_completion "completions/harvest.bash"
  fish_completion "completions/harvest.fish"
  zsh_completion "completions/harvest.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harvest"]
    end
  end

  # No zap stanza required

end
