# This file was generated by GoReleaser. DO NOT EDIT.
cask "harvest-cli" do
  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "e2bd8e91ce9ba1579f5a54f9ad01d6093cd7d3213ae249671f747568047276a5"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0d16754faaa92338ac77b063b6854b13e041561838664751d39f831aa438e74"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a784125cc28ec367e15a91824166facbad7c9e6e194a26c14902ba031f59c08"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7eb0748b13efbe81b11ad74219dbc89c1cd45b30611732117628bf37a6db9917"
      url "https://github.com/jc00ke/harvest/releases/download/v#{version}/harvest_linux_amd64.tar.gz"
    end
  end

  name "harvest-cli"
  desc "A command-line tool for managing your Harvest time entries, projects, and tasks"
  homepage "https://github.com/jc00ke/harvest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harvest"
  bash_completion "completions/harvest.bash"
  fish_completion "completions/harvest.fish"
  zsh_completion "completions/harvest.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/harvest"]
    end
  end

  # No zap stanza required
end
